Reworked ROS Interface
knowrob/knowrob pull request #393
Opened 2024-05-03 13:15 UTC by sasjonge

This PR fixes the ROS Interface. It now builds with catkin and offers multiple interfaces when run with `roslaunch knowrob knowrob.launch`.

I renamed the project in package.xml and CMakelists from KnowRob to knowrob, because i got build warnings that the project name should be in lower case. 

The class InterfaceUtils.cpp have some common function other interfaces could also use, e.g. a rest interface.

It tested the 5 interfaces with a local integration test, at a later point we could have a look at an automatic testing of the interfaces via CI.

2024-05-08 10:16 UTC, daniel86 requested changes
Looks good, overall just a few small comments. Please run auto formatting

2024-05-08 10:16 UTC, daniel86 commented on CMakeLists.txt
> +option(BUILD_WITH_CATKIN "Build the interface for ROS1 systems" ON)
Isn't catkin used by ROS2 too? I would vote calling the option "WITH_ROS1" or "WITH_ROS1_INTERFACE"

2024-05-08 10:16 UTC, daniel86 commented on CMakeLists.txt
> +            DIRECTORY action
maybe we should move actions also into a ros1 folder?

2024-05-08 10:16 UTC, daniel86 commented on include/knowrob/integration/ros1/ROSInterface.h
> +		std::mutex query_mutex_;
i think indentation is wrong here. maybe run auto-format on the changed files

2024-05-08 10:16 UTC, daniel86 commented on include/knowrob/queries/QueryParser.h
> +#include "boost/any.hpp"
seems not needed, or move into source file if needed there

2024-05-08 10:16 UTC, daniel86 commented on include/knowrob/integration/InterfaceUtils.h
> +		static bool assertStatements(const KnowledgeBase kb_, const std::vector<FormulaPtr> &args);
`kb_` is copied here, better pass in by reference

2024-05-08 10:16 UTC, daniel86 commented on include/knowrob/integration/ros1/ROSInterface.h
> +		actionlib::SimpleActionServer <AskIncrementalNextSolutionAction> askincremental_next_solution_action_server_;
intendation

2024-05-08 10:16 UTC, daniel86 commented on src/integration/InterfaceUtils.cpp
> +		KB_INFO("[KnowRob] aboutAgentIRI.");
seems like debug output that should be removed

2024-05-10 09:30 UTC, sasjonge commented
I fixed all your comments. The identation seems also to be not completly broken anymore after i autoformatted the files.

2024-05-15 15:04 UTC, daniel86 approved these changes

2024-05-15 15:04 UTC, merged