Propertytree handling in Python
knowrob/knowrob pull request #406
Opened 2024-07-31 14:09 UTC by sasjonge

With this PR i improved the Propertytree handling in python, and also allowed the loading from settings from a python dict.

2024-07-31 14:47 UTC, daniel86 requested changes
Looks good! but there is a memory leak that should be fied

2024-07-31 14:47 UTC, daniel86 commented on include/knowrob/PropertyTree.h
> +		explicit PropertyTree(const std::string &json_str);
minor comment: usually it is better to use string_view. Reason: you can call the function then either with string or string_view (string can implicitly be casted to string_view but not the other way around!)

2024-07-31 14:47 UTC, daniel86 commented on src/PropertyTree.cpp
> +	ptree_ = new boost::property_tree::ptree(tree);
there is a memory leak here because no one calls **delete ptree_**.
You can also not just call delete in the destructor because in the case above PropertyTree *is not the owner*. So you could add another flag indicating whether delete must be called in the destructor.

2024-07-31 14:47 UTC, daniel86 commented on src/ontologies/DataSource.cpp
> +		register_ptr_to_python< std::shared_ptr< DataSource > >();
so this is really needed?

2024-07-31 17:02 UTC, sasjonge commented on src/PropertyTree.cpp
> +	ptree_ = new boost::property_tree::ptree(tree);
i changed ptree_ now to be a smart pointer

2024-08-01 05:35 UTC, daniel86 commented on include/knowrob/PropertyTree.h
> +		explicit PropertyTree(const std::string_view &json_str);
minor: You should not use by reference for string_view, always pass string_view by value

@see https://quuxplusone.github.io/blog/2021/11/09/pass-string-view-by-value/

2024-08-01 05:37 UTC, daniel86 approved these changes

2024-08-01 11:01 UTC, merged